### ISSUE TITLE
Exec macros by keybinding

### ISSUE THREAD

**Issue by notiv-nt** [JunSuzukiJapan/atom-keyboard-macros#8]
Hello, is there any way to exec file by keybind ?

Like sublime`s:

```
{
    "keys": ["ctrl+alt+k"],
    "command": "run_macro_file",
    "args": {
        "file": "Packages/User/log.sublime-macro"
    }
}

```

**Comment by JunSuzukiJapan** [comment]
Hi.

It does not have that function.

Instead, How about to give a name to the macro, as below.
1. Using 'atom-keyboard-macros:name_last_kbd_macro', give a name to the macro.
2. Save macros.
3. Add keybind to your 'keymap.cson' file.
   
   ```
   '.workspace':
    'ctrl-alt-k': 'atom-keyboard-macros.user:<your macro name>'
   ```

In this way, you can use your macros just to load macros.

**Comment by notiv-nt** [comment]
@JunSuzukiJapan
Yes, it works, but how i can store\exec macro to\from file?
After reloading atom the macros do not work.

**Comment by JunSuzukiJapan** [comment]
It might not work depending on the version of the atom.
I will investigate it.

**Comment by JunSuzukiJapan** [comment]
I fixed it.
Try v0.8.4, please.

Thank you.

**Comment by notiv-nt** [comment]
No, it still does not work after restart atom (

And i can't find there is it stored

**Comment by JunSuzukiJapan** [comment]
Please tell me the operations that has been recorded in your macro.

**Comment by notiv-nt** [comment]
For example:

In sublime i have:

Keybind:

``` json
{
    "keys": ["ctrl+alt+p"],
    "command": "run_macro_file",
    "args": {
        "file": "Packages/User/rem.sublime-macro"
    }
}
```

File:

``` json
[
  {
    "args":
    {
      "characters": "_rem("
    },
    "command": "insert"
  },
  {
    "args":
    {
      "by": "word_ends",
      "forward": true
    },
    "command": "move"
  },
  {
    "args":
    {
      "characters": ")"
    },
    "command": "insert"
  }
]
```

And used here as example:

``` css
body {
  padding: 20px;
}
```

And if i place cursor on `20px` and press ctrl+alt+p, it wraps `20px` into `_rem(20px)`

If i record macro at atom and save it, it will looks like:

```
>
*D
:editor:move-to-beginning-of-word
*I
:_
:r
:e
:m
:(
*D
:editor:move-to-end-of-word
*I
:)
```

**Comment by JunSuzukiJapan** [comment]
First, macro name is not filename.
Second, you can store a lot of macros to one file.

After recording macro, you should give a name to the macro using 'atom-keyboard-macros:name_last_kbd_macro'.

If save it, it will looks like:

```
>macroname
*D
:editor:move-to-beginning-of-word
*I
:_
:r
:e
:m
:(
*D
:editor:move-to-end-of-word
*I
:)
```

**Comment by notiv-nt** [comment]
It does not works

**Comment by AbdelrahmanHafez** [comment]
Do I have to load my macros every time open Atom to use them? If that's the case, it would be great to be automatically loaded.

I made a macro to make EJS tags for me, and attached them to a shortcut, but the catch is I can't use them before manually loading my macro file every time I start Atom. Am I doing something wrong? If not, I hope you could fix that in the next version.

Currently running on Atom v1.10.0, and atom-keyboard-macros v0.9.2
@JunSuzukiJapan

**Comment by inigopascall** [comment]
I have this problem too. I don't get it... I really need to go the the package menu and load EACH of my (potentially hundreds of) saved macros before I can use them...?? Am I missing something?
